networks:
  mims-net:
    name: mims-net

volumes:
  mims-redis-data:
    name: mims-redis-data

services:
  mims-catalog:
    container_name: mims-catalog
    build:
      context: .
      args:
        - CA_CERT_URL
    networks:
      - mims-net
    ports:
      - "4023:4023"
    #extra_hosts:  # dev platform
    #  - "odp2.saeon.dvn:192.168.115.71"
    environment:
      - ODP_ENV
      - FLASK_ENV=${ODP_ENV}
      - MIMS_CATALOG_FLASK_SECRET
      - MIMS_CATALOG_CI_CLIENT_ID
      - MIMS_CATALOG_CI_CLIENT_SECRET
      - MIMS_CATALOG_UI_CLIENT_ID
      - MIMS_CATALOG_UI_CLIENT_SECRET
      - ODP_API_URL
      - ODP_ADMIN_URL
      - HYDRA_PUBLIC_URL
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips=*
      - REDIS_HOST=redis
      - TZ
      - PYTHONUNBUFFERED=1
    restart: always

  redis:
    container_name: mims-redis
    image: redis:6
    networks:
      - mims-net
    volumes:
      - mims-redis-data:/data
    restart: always
